log    = /scratch/mkim/wipac_full/logs/A$(station).R$(run).log
output = /scratch/mkim/wipac_full/logs/A$(station).R$(run).out
error  = /scratch/mkim/wipac_full/logs/A$(station).R$(run).err

request_memory = 4GB
#request_disk = 10GB

Universe = vanilla
getenv = true
+TransferOutput = ""
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

nice_user = false

executable = ARA_job.sh
arguments = $(station) $(run)

queue
