log    = /scratch/mkim/Sim/R$(station)_real_norm.log
output = /scratch/mkim/Sim/R$(station)_real_norm.out
error  = /scratch/mkim/Sim/R$(station)_real_norm.err

#request_gpus = 1
request_memory = 4GB
#request_memory = 8GB
Universe = vanilla
getenv = true
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

nice_user = false

executable = ARA_job_real_norm.sh
arguments = $(data) $(ped) $(station)

queue
