log    = /scratch/mkim/wipac_sim_signal/logs/A$(st).R$(run).F$(fla).log
output = /scratch/mkim/wipac_sim_signal/logs/A$(st).R$(run).F$(fla).out
error  = /scratch/mkim/wipac_sim_signal/logs/A$(st).R$(run).F$(fla).err

request_memory = 1GB

Universe = vanilla
getenv = true
+TransferOutput = ""
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

nice_user = false

executable = ARA_job.sh
arguments = $(st) $(run) $(fla)

queue
