log    = /scratch/mkim/wipac_repeder_grappa/logs/A$(station).R$(run).log
output = /scratch/mkim/wipac_repeder_grappa/logs/A$(station).R$(run).out
error  = /scratch/mkim/wipac_repeder_grappa/logs/A$(station).R$(run).err

request_memory = 5GB

Universe = vanilla
getenv = true
+TransferOutput = ""
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

nice_user = false

executable = ARA_job.sh
arguments = $(data) $(station) $(run)

queue
