log    = /scratch/mkim/wipac_sim_signal_mono/logs/A$(st).E$(energy).SR$(sim_run).log
output = /scratch/mkim/wipac_sim_signal_mono/logs/A$(st).E$(energy).SR$(sim_run).out
error  = /scratch/mkim/wipac_sim_signal_mono/logs/A$(st).E$(energy).SR$(sim_run).err

request_memory = 1GB

Universe = vanilla
getenv = true
+TransferOutput = ""
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

nice_user = false

executable = ARA_job.sh
arguments = $(st) $(energy) $(sim_run)

queue
