log    = /scratch/mkim/wipac_est/logs/A$(station).P$(pol).S$(slo).F$(frac).log
output = /scratch/mkim/wipac_est/logs/A$(station).P$(pol).S$(slo).F$(frac).out
error  = /scratch/mkim/wipac_est/logs/A$(station).P$(pol).S$(slo).F$(frac).err

request_memory = 2GB

Universe = vanilla
getenv = true
+TransferOutput = ""
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

nice_user = false

executable = ARA_job.sh
arguments = $(station) $(pol) $(slo) $(frac)

queue
