log    = /scratch/mkim/MF_filters/ARA0$(station).Run$(run).log
output = /scratch/mkim/MF_filters/ARA0$(station).Run$(run).out
error  = /scratch/mkim/MF_filters/ARA0$(station).Run$(run).err

#request_cpus = 1
request_memory = 16GB
#request_disk = 2GB
Universe = vanilla
getenv = true
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

nice_user = false

executable = ARA_job.sh
arguments = $(data) $(ped) $(station) $(run) $(out) $(mode)

queue
