log    = /scratch/mkim/wipac_sim_signal/logs/A$(st).C$(config).R$(run).$(flavor).log
output = /scratch/mkim/wipac_sim_signal/logs/A$(st).C$(config).R$(run).$(flavor).out
error  = /scratch/mkim/wipac_sim_signal/logs/A$(st).C$(config).R$(run).$(flavor).err

request_memory = 1GB

Universe = vanilla
getenv = true
+TransferOutput = ""
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

nice_user = false

executable = ARA_job.sh
arguments = $(setup) $(run) $(st)

queue
