log    = /scratch/mkim/wipac_sim_temp_config/logs/A$(st).R$(run).SR$(sim_run).log
output = /scratch/mkim/wipac_sim_temp_config/logs/A$(st).R$(run).SR$(sim_run).out
error  = /scratch/mkim/wipac_sim_temp_config/logs/A$(st).R$(run).SR$(sim_run).err

request_memory = 1GB

Universe = vanilla
getenv = true
+TransferOutput = ""
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

nice_user = false

executable = ARA_job.sh
arguments = $(st) $(run) $(sim_run)

queue
