echo "before :("
echo "ARA_UTIL_INSTALL_DIR = "${ARA_UTIL_INSTALL_DIR}
echo "LD_LIBRARY_PATH = "${LD_LIBRARY_PATH}

export ARA_UTIL_INSTALL_DIR=/home/mkim/analysis/AraSoft/AraUtil
export LD_LIBRARY_PATH=${ARA_UTIL_INSTALL_DIR}/lib:$LD_LIBRARY_PATH

echo "after  :)"
echo "ARA_UTIL_INSTALL_DIR = "${ARA_UTIL_INSTALL_DIR}
echo "LD_LIBRARY_PATH = "${LD_LIBRARY_PATH}


